version: "3.8"

services:
  devirl-auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devirl-auth-service-app
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: dev_quest
      DB_USER: dev_quest_user
      DB_PASSWORD: turnip
    ports:
      - "8080:8080"
    networks:
      - dev-irl-network

networks:
  dev-irl-network:
    external: true
